In [2]:
import torch

In [3]:
tensor = torch.tensor([1,2,3])

### Matrix multiplication
using for loop

In [4]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print (value)

tensor(14)
CPU times: total: 15.6 ms
Wall time: 57.7 ms


### Pytorch matmul()

In [5]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 10.1 ms


tensor(14)

### Rules for Matrix Multiplication
1. Number of columns in first matrix must be equal to number of rows in the second matrix
2. Resultant matrix is the of the dimensions row (of first matrix) x columns (of second matrix)

In [29]:
tensor_a = torch.randint(0,10,(3,3))
tensor_b = torch.randint(0,10,(3,2))
tensor_a.shape, tensor_b.shape

(torch.Size([3, 3]), torch.Size([3, 2]))

In [15]:
torch.matmul(tensor_a,tensor_b)

tensor([[ 32,  66],
        [ 21,  70],
        [ 46, 125]])

### Tensor Transpose

In [36]:
tensor_c = torch.randint(0,10,(2,3))
tensor_c.shape #cannot be multiplied with either tensor_a or tensor_b
# torch.matmul(tensor_a, tensor_c) is not possible
# If we transpose tensor_c, then matrix multiplication is possible

torch.Size([2, 3])

In [38]:
# tensor.T is for transpose
tensor_c.T


tensor([[1, 9],
        [4, 5],
        [2, 9]])

In [39]:
torch.matmul(tensor_a, tensor_c.T)

tensor([[ 42,  85],
        [ 33, 101],
        [ 48, 135]])

### Tensor Aggregation (min, max, mean, sum...)

In [45]:
# Mean - does not work with floating point or comolex dtypes
# therefore torch.mean(tensor) will not work until the dtype
# is changed, which can be changed using tensor.type(torch.float32/64/16/..)

torch.mean(tensor_a.type(torch.float32))

tensor(5.)

In [49]:
torch.max(tensor_a), torch.min(tensor_a), torch.sum(tensor_a)

(tensor(9), tensor(0), tensor(45))

### To find the index of the min,max element use torch.argmin/argmax

In [51]:
tensor_a, torch.argmin(tensor_a), torch.argmax(tensor_a)

(tensor([[0, 8, 5],
         [1, 4, 8],
         [8, 9, 2]]),
 tensor(0),
 tensor(7))

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other or side by side  
* Sueeze - removes all `1` dimenions from a tensor
* Unsqueeze - add `1` dimension to a target tensor
* Permute - Return a view of the input with dims permuted (swapped) in a certain way

In [53]:
# creating new tensor
x = torch.arange(1.,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [55]:
# adding a dim
x_mod = x.reshape(9,1)
x_mod

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [58]:
z = x.view(1,9) # z shares the same memory as x. Think of view making z act as pointer

In [59]:
#changing z changes x because view of tensor shares the same memory as original input
z[:,0] = 5
z


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

### Stack

In [65]:
# torch.stack() takes a list as input vstack = dim0 hstack = dim1
x_stack = torch.stack([x,x,x,x], dim=0) # try dim=1 too
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

### Squeeze and Unsqueeze

In [81]:
x_mod.shape

torch.Size([9, 1])

In [84]:
# removes `1` dimension
torch.squeeze(x_mod).shape

torch.Size([9])

In [86]:
x_mod.shape

torch.Size([9, 1])

In [91]:
torch.unsqueeze(x, dim=1).shape

torch.Size([9, 1])

### Permute - rearranges the dims of target tensor in specified order (mostly used for images)

In [96]:
x_permute = torch.randn(2,3,5) # makes 2 tensors whose values
#are chosen randomly from normal distribution of mean = 0 and 
#std dev = 1
# TL;DR - makes 2 tensors with random values of 3x5 dim
x_permute

tensor([[[-0.7609,  0.3658, -1.6991, -0.5185,  0.2154],
         [-0.0425, -0.6977, -1.0485, -0.8928, -1.0591],
         [-0.8069, -0.8556, -0.1423,  0.0188,  1.0306]],

        [[-1.0290, -0.5005, -1.0202, -1.0485, -0.2578],
         [-1.2653,  0.1852,  0.3862, -0.1295, -0.1571],
         [ 1.2576, -0.2811,  0.8668, -0.2180,  0.6796]]])

In [108]:
original_image = torch.rand(size=(224,224,3))
# height = 224, width = 224, colour =3

permuted_index  = torch.permute(original_image,dims=(2,0,1))
# 2nd column is placed at 0th index, 0th is placed at 1st and 1st ast 3rd


In [109]:
original_image.shape, permuted_index.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))