In [2]:
import torch
import matplotlib as plt
import pandas as pd
import numpy as np
print(torch.__version__)

2.3.0+cu121


## Introduction to Tensors

### Creating Tensors

In [3]:
#scalar - only magnitude
scalar = torch.tensor(7)
print(scalar)


tensor(7)


In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# dimensions of scalar
scalar.ndim

0

In [6]:
# Vector - magnitude + direction
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
# vector dimension
vector.ndim

1

In [8]:
Tensor = torch.tensor([[
                        [1,2,3,4],
                        [4,5,6,9],
                        [7,8,9,16]]],
                        )
Tensor

tensor([[[ 1,  2,  3,  4],
         [ 4,  5,  6,  9],
         [ 7,  8,  9, 16]]])

In [9]:
Tensor.ndim
# Tensor.shape

3

In [10]:
Tensor[0][2][1] 

tensor(8)

### Random Tensors

Why random tensors -> Important for neural networks. They start with tensors full of random numbers and then adjust those random numbers to better represent the data

In [11]:
#creating a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8279, 0.0302, 0.0058, 0.9528],
        [0.7658, 0.6002, 0.5829, 0.2419],
        [0.1650, 0.5624, 0.6258, 0.3647]])

In [12]:
random_tensor.ndim

2

In [13]:
# random tensor similiar to an image tensor 
random_tensor_image = torch.rand(size=(3,224,224)) # colour channels (R,G,B), height, width
random_tensor_image.shape, random_tensor_image.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [14]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
#Tensors of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

In [18]:
random_tensor.dtype

torch.float32

### Create a range of tensors

In [19]:
# using torch.range()
range = torch.arange(0,10,1)
range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#using tensors._like()
ten_zeros = torch.zeros_like(range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor datatype

In [21]:
# float32 tensor
float32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype=None, # datatype of tensor e.g. float32, float64, etc.
                              device=None,
                              requires_grad=False) 

### Tensor Operations
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication

In [24]:
# Create a tensor and add 10 to it
Tensor + 10

tensor([[[11, 12, 13, 14],
         [14, 15, 16, 19],
         [17, 18, 19, 26]]])

In [28]:
# subtract 1 from tensor
Tensor - 1

tensor([[[ 0,  1,  2,  3],
         [ 3,  4,  5,  8],
         [ 6,  7,  8, 15]]])

In [30]:
# Multiply
Tensor * 10

tensor([[[ 10,  20,  30,  40],
         [ 40,  50,  60,  90],
         [ 70,  80,  90, 160]]])

In [35]:
# Pytorch in-built functions
torch.mul(Tensor,10), torch.add(Tensor,10)

(tensor([[[ 10,  20,  30,  40],
          [ 40,  50,  60,  90],
          [ 70,  80,  90, 160]]]),
 tensor([[[11, 12, 13, 14],
          [14, 15, 16, 19],
          [17, 18, 19, 26]]]))

### Matrix Multiplication (dot product)

In [52]:
dot_tensor = torch.tensor([1,2,3])
torch.matmul(dot_tensor, dot_tensor), len(dot_tensor)

(tensor(14), 3)